name: Build AalooPower

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Java 17 (Minecraft 1.21.4 compatible)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: .  # ensure correct folder

      # 4️⃣ Upload jar artifact
      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AalooPower-jar
          path: target/*.jar
