name: Build AalooPower

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: AalooPower-jar
          path: target/*.jar
