name: Build AalooPower

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Get commit info
      - name: Get commit info
        id: vars
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

      # 4️⃣ Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: .

      # 5️⃣ Upload jar artifact with commit info in name
      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AalooPower-${{ env.COMMIT_SHA }}-${{ env.COMMIT_AUTHOR }}
          path: target/*.jar
